### ISSUE TITLE
The deployment problem

### ISSUE THREAD

**Issue by KungZell** [rajahaseeb147/HeadLocation#1]
Hello， @pytholic 
Thank you for the open source project.
How should the project be deployed and how should it perform in real time?

**Comment by pytholic** [comment]
Hi. Actually I prepared the `coreml` model and gave it to one of my colleagues to work on the iOS deployment part. We then tested it on **iPad pro 11**.

I managed to fetch some of the deployment code [here](https://github.com/pytholic/Patient_Pose_Detection_Depth_Images/blob/main/Implementation/DetectPose.swift). I am not sure if it is the complete code, but hopefully. I did it last year so memory is kind of hazy. 

The performance was fine with both `ResNet` and `MobileNet`. Maybe it depends on the application. For my case I just needed a label of patient's orientation so speed was good enough.

Hope it helps!

**Comment by pytholic** [comment]
> Hello， @pytholic Thank you for the open source project. How should the project be deployed and how should it perform in real time?

Hi. Actually I prepared the `coreml` model and gave it to one of my colleagues to work on the iOS deployment part. We then tested it on **iPad pro 11**.

I managed to fetch some of the deployment code [here](https://github.com/pytholic/Patient_Pose_Detection_Depth_Images/blob/main/Implementation/DetectPose.swift). I am not sure if it is the complete code, but hopefully. I did it last year so memory is kind of hazy. 

The performance was fine with both `ResNet` and `MobileNet`. Maybe it depends on the application. For my case I just needed a label of patient's orientation so speed was good enough. It will just give you a label representing patient's pose in real-time.

you can follow same format to get any other output besides patient's orientation. Basically it is just image classification.

Hope it helps!

**Comment by KungZell** [comment]
Thanks for your prompt reply, I was actually looking for an example of using a depth camera to detect attitude in real time. Anyway, thank you very much for your help.
Best regards.

**Comment by pytholic** [comment]
> Thanks for your prompt reply, I was actually looking for an example of using a depth camera to detect attitude in real time. Anyway, thank you very much for your help. Best regards.



> Thanks for your prompt reply, I was actually looking for an example of using a depth camera to detect attitude in real time. Anyway, thank you very much for your help. Best regards.

We have our application and we use Occipital Structure Sensor with it. This model is used inside that application to detect pose.

I cannot share details or code of our Application because it is not open-source and also it has a lot of parts and stuff.
